### ISSUE TITLE
rpm packages with same version but different releases are not distinguished and conflict

### ISSUE THREAD

**Issue by bcrowe-gs** [openkilt/openrepo#7]
RPM packages have a version and a release - generally within the name: `<version>-<release>.`   But openrepo only considers the version, so if you upload same version but newer release, it will conflict with the older release, and unless you specify overwrite then it will fail.  In our use-case we want to retain some older releases in the repository so we can rebuild prior versions. We can adopt to using only version (adding a new .`<microversion>`) but there are lots of pre-existing RPMs with the `<version>-<release>` convention and supporting this would be a good thing IMO.

**Comment by matthill** [comment]
Thank you for filing this bug report.  Just to make it easier to reproduce, can you send two sample RPMs that can show the issue?

**Comment by bcrowe-gs** [comment]
Attaching two files that demonstrate this. These are found at https://rpmfind.net/linux/rpm2html/search.php?query=glibc 
[glibc-rpms.tgz](https://github.com/openkilt/openrepo/files/11116111/glibc-rpms.tgz)

**Comment by bcrowe-gs** [comment]
Thinking about this - I think there are some use cases where the current behaviour is probably desired, so you can enforce only one rpm at each version number, I could see that might help keep a cleaner repo.   Maybe an option for the repo to uniquely identify rpms based on version alone, or version+release ?  Just a thought.

**Comment by matthill** [comment]
I think you're right, the most sensible version number would also include the build number.  It may make version comparison more difficult though, since RPMs can have unstructured values in the build ID (i.e., the build number can be a string not just a number). Which makes promotion more difficult.

I changed the default behavior to include the build number, which I believe is what you want.  And it can be disabled (i.e., the old behavior of just the major/minor version) by setting this environment variable before starting the server:
RPM_VERSION_IGNORE_BUILD_NUM=True
